### ISSUE TITLE
luck.org.pl not avaliable

### ISSUE THREAD

**Issue by piotrkorlaga** [luck-js/luck-ui#21]
https://www.luck.org.pl/ - works 👍 
https://luck.org.pl/ - does not work 👎 
http://luck.org.pl/ - does not work 👎  👉 https://screencast.com/t/npo4VVj5

**Comment by dkarski** [comment]
Hi @piotrkorlaga,

thanks for your issue! 👍Our team dealt with this issue at the speed of a comet 🎉 

https://www.luck.org.pl/ - works 👍
https://luck.org.pl/ - works 👍
http://www.luck.org.pl/ - works 👍
http://luck.org.pl/ - works 👍

https://github.com/luck-js/luck-ui/pull/36
